/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
/**
 *
 * @author sergio
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuInventario
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtRegistro = new javax.swing.JButton();
        BtSalir = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        BtInventario = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtRegistro.setBackground(new java.awt.Color(255, 255, 255));
        BtRegistro.setText("Registro");
        BtRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegistroActionPerformed(evt);
            }
        });
        getContentPane().add(BtRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 270, 120));

        BtSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtSalir.setText("Salir");
        BtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtSalirMouseClicked(evt);
            }
        });
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 580, 240, 120));

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/output-onlinepngtools.png"))); // NOI18N
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        BtInventario.setBackground(new java.awt.Color(255, 255, 255));
        BtInventario.setText("Inventario");
        BtInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtInventarioMouseClicked(evt);
            }
        });
        BtInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtInventarioActionPerformed(evt);
            }
        });
        getContentPane().add(BtInventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 240, 120));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setIcon(new javax.swing.ImageIcon("/Users/sergio/Downloads/imágenes/trees3/trees3.001.png")); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -90, 830, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BtSalirActionPerformed

    private void BtRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegistroActionPerformed
        // TODO add your handling code here:
        MenuRegistro mr = new MenuRegistro();
        mr.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtRegistroActionPerformed

    private void BtInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtInventarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtInventarioActionPerformed

    private void BtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BtSalirMouseClicked

    private void BtInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtInventarioMouseClicked
        // TODO add your handling code here:
        MenuInventario mi = new MenuInventario();
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtInventarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtInventario;
    private javax.swing.JButton BtRegistro;
    private javax.swing.JButton BtSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    // End of variables declaration//GEN-END:variables
}
