

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import pantallas.*;
import jxl.*;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.read.biff.BiffException;
import static org.apache.commons.math3.fitting.leastsquares.LeastSquaresFactory.model;
import org.apache.poi.hssf.usermodel.*;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.DataFormat;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author sergio
 */
public class InLibros extends javax.swing.JFrame {

    /**
     * Creates new form blabla
     */
    private static DefaultTableModel model = new DefaultTableModel();

    public InLibros() {
        initComponents();
        
        Tabla.setModel(model);
    }
    
    private void ImportarExcel (){
        File archivoExcel = new File ("/Users/sergio/eclipse-workspace/InventarioAtrsalante/excel.xls");
        try {
            Workbook excel = Workbook.getWorkbook(archivoExcel);
            Sheet hoja = excel.getSheet(0);
            int columnas = hoja.getColumns();
            int filas = hoja.getRows();
            Object datos[] = new Object[columnas];
            
            for(int fila = 0; fila<filas; fila++){
                for(int columna = 0; columna<columnas; columna++){
                    
                    if (fila == 0){
                        model.addColumn(hoja.getCell(columna, fila).getContents());
                    }
                    
                    if (fila>=1){
                        datos[columna] = hoja.getCell(columna, fila).getContents();
                    }
                }
                model.addRow(datos);
                
            }
            model.removeRow(0);

            
            
            

            
        } catch (IOException | BiffException ex) {
            Logger.getLogger(InLibros.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
        
        
        
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtRegresar = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtRegresar.setBackground(new java.awt.Color(255, 255, 255));
        BtRegresar.setFont(new java.awt.Font("Nanum Gothic", 0, 13)); // NOI18N
        BtRegresar.setText("Regresar");
        BtRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtRegresarMouseClicked(evt);
            }
        });
        BtRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BtRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 120, 50));

        LblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("Libros");
        LblTitulo.setToolTipText("");
        getContentPane().add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        Tabla.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla.setSelectionBackground(new java.awt.Color(153, 153, 255));
        Tabla.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(Tabla);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 550, 180));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 130, 50));

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setIcon(new javax.swing.ImageIcon("/Users/sergio/Downloads/imágenes/trees3/trees3.001.png")); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -90, 830, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRegresarActionPerformed
        MenuInventario mi = new MenuInventario();
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtRegresarActionPerformed

    private void BtRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtRegresarMouseClicked
        // TODO add your handling code here:
        MenuInventario mi = new MenuInventario();
        mi.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtRegresarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImportarExcel();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InLibros().setVisible(true);
                
            }
        });
        

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtRegresar;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
