/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import pantallas.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sergio
 */
public class ReLibros extends javax.swing.JFrame {

    /**
     * Creates new form blabla
     */
    public ReLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtSalir = new javax.swing.JButton();
        LblTitulo = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        LblTitulo1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        LblTitulo2 = new javax.swing.JLabel();
        LblTitulo3 = new javax.swing.JLabel();
        LblTitulo4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtSalir.setBackground(new java.awt.Color(255, 255, 255));
        BtSalir.setFont(new java.awt.Font("Nanum Gothic", 0, 13)); // NOI18N
        BtSalir.setText("Regresar");
        BtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtSalirMouseClicked(evt);
            }
        });
        BtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BtSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 120, 50));

        LblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo.setText("Año:");
        LblTitulo.setToolTipText("");
        getContentPane().add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 180, 50));

        jComboBox1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 140, 40));

        LblTitulo1.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        LblTitulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo1.setText("Nuevo libro");
        LblTitulo1.setToolTipText("");
        getContentPane().add(LblTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 200, 30));

        LblTitulo2.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LblTitulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo2.setText("Categoría:");
        LblTitulo2.setToolTipText("");
        getContentPane().add(LblTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 180, 50));

        LblTitulo3.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LblTitulo3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo3.setText("Libro:");
        LblTitulo3.setToolTipText("");
        getContentPane().add(LblTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 180, 50));

        LblTitulo4.setBackground(new java.awt.Color(255, 51, 51));
        LblTitulo4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        LblTitulo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblTitulo4.setText("Autor:");
        LblTitulo4.setToolTipText("");
        getContentPane().add(LblTitulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 180, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 200, 30));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 200, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Confirmar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 120, 40));

        Fondo1.setBackground(new java.awt.Color(255, 255, 255));
        Fondo1.setIcon(new javax.swing.ImageIcon("/Users/sergio/Downloads/imágenes/trees3/trees3.001.png")); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -90, 830, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalirActionPerformed
        
    }//GEN-LAST:event_BtSalirActionPerformed

    private void BtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtSalirMouseClicked
        // TODO add your handling code here:
        MenuRegistro mr = new MenuRegistro();
        mr.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtSalir;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel LblTitulo1;
    private javax.swing.JLabel LblTitulo2;
    private javax.swing.JLabel LblTitulo3;
    private javax.swing.JLabel LblTitulo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
